### ISSUE TITLE
Document Checklist

### ISSUE THREAD

**Issue by duythanhvn** [funix-lab/contribution-guide#1]
- [ ] Open Source Guide
- [ ] Git Pro, 2 Edition (eBook)
- [ ] Open Source License Guide
- [ ] Tower Software Guide
- [ ] Collaboration Skill
